### ISSUE TITLE
CAN Timeout Detection

### ISSUE THREAD

**Issue by sharrington93** [BuckeyeCurrent/MCN-Software#17]
Need to implement code that can detect when a CAN message isn't received within a set period of time. If it isn't, we need to set throttle output to 0 and wait until we receive the missing message again before restoring throttle. (We should maybe check that we receive 2 or 3 before restoring throttle again).

Example of doing CAN timeout for a different project: https://github.com/sharrington93/Battery-balancer/blob/master/Software/Battery%20Balancer/Project%20Source/CAN.c

**Comment by SoMuchHat** [comment]
@davidemoeller this does not work currently. When testing the software on your latest commit (https://github.com/davidemoeller/MCN-Software/commit/50fde27f6840a9d48f67dac2774fa89a5d06d958) I am sending none of the temperature messages over CAN but I can still see a throttle output (should be 0 if you aren't receiving a cell temperature within 3 seconds)

**Comment by SoMuchHat** [comment]
@davidemoeller I believe this is resolved actually. I did a reflash on the board and the throttle is now 0 when I don't send messages.

**Comment by SoMuchHat** [comment]
@davidemoeller reopening because I'm still seeing this issue.

**Comment by SoMuchHat** [comment]
@davidemoeller with your latest commit, I'm seeing the following:

If I start up the application with no cell temperatures sending, the timeout will kick in after 3 seconds. However, if I then start sending all the cell temperature messages, the timeout never goes away. 

If I start up the application with all the cell temperatures sending, the module will not go into timeout as expected. If I then go in and stop sending message ID 0x350, the timeout will kick in. If I then go back and start sending the message again, the timeout will go away as expected. If I repeat the same procedure but stop sending any other cell temperature, let it timeout, and then try sending that cell temperature again, the timeout gets stuck.

**Comment by SoMuchHat** [comment]
I believe this is working now. Will reopen if I see the problem reoccur.
